### ISSUE TITLE
Check .env.example file

### ISSUE THREAD

**Issue by phahulin** [poanetwork/token-bridge#100]
Please check values given in .env.example file. Both in `master` and in `support-erc20-native-#81` branches.

Things I noticed:

1. `VALIDATOR_ADDRESS` is not used and should be removed
2. `HOME_GAS_PRICE_FALLBACK`, `FOREIGN_GAS_PRICE_FALLBACK` should be set in wei, so it's better to use `1000000000` as default.

**Comment by akolotov** [comment]
Addressed in #85.
