### ISSUE TITLE
Run a watchdog timer in watchers

### ISSUE THREAD

**Issue by fvictorio** [poanetwork/token-bridge#105]
The watchers of a deployed bridge instance have had issues in which they stop listening. We are not sure about what's happening, but to alleviate the issue we need to add a watchdog that kills the process if the watcher function doesn't return after a given amount of time.

Killing the process has an edge case where it causes a problem: if it's killed after the jobs are sent to rabbit but before the last processed block is updated in redis, the transactions involved may get sent twice. This is very unlikely, and the only downside is making the validators waste gas, so it's acceptable for now.

**Comment by akolotov** [comment]
Addressed in #106
