### ISSUE TITLE
Script to return Ethereum address from a private key 

### ISSUE THREAD

**Issue by akolotov** [poanetwork/token-bridge#107]
In order to provide configuration for the token bridge watchers, the deployment playbook needs to calculate an Ethereum address from a private key (for more details see https://github.com/poanetwork/deployment-bridge/issues/36).

Consider to implement a script (similar to scripts/getValidatorStartBlocks.js) that will get a private key from the environment variable (`.env`-file) and return an Ethereum address corresponding to the private key.

**Comment by fvictorio** [comment]
Done in https://github.com/poanetwork/token-bridge/pull/85/commits/a8c795d7742fc048828e09dc328e4392f688fe3a as part of https://github.com/poanetwork/token-bridge/pull/85.
