### ISSUE TITLE
NetworkId is confused with chainId

### ISSUE THREAD

**Issue by rosulucian** [poanetwork/token-bridge#134]
```getChainID``` in ```\src\tx\web3.js``` returns network id instead of chainId.

This can lead to ```invalid sender``` errors for certain network config.

 I fixed it on my side by wrapping rpc ```eth_chainId```

**Comment by akolotov** [comment]
Thanks! Could you prepare a PR against the `develop` branch as so we could accept your changes?

**Comment by akolotov** [comment]
Changes merged to the master branch
