### ISSUE TITLE
Separate `.env` in diferent files

### ISSUE THREAD

**Issue by fvictorio** [poanetwork/token-bridge#32]
See [this comment](https://github.com/poanetwork/bridge-nodejs/pull/27#issuecomment-398379356)

Use a `public.env` file for public variables that can be committed, and a `.env` (not commited) file for private variables.

**Comment by akolotov** [comment]
It is not applicable any more, it was addressed in [the release 1.1.0](https://github.com/poanetwork/token-bridge/releases/tag/1.1.0)
