### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by phahulin** [poanetwork/token-bridge#79]
Please re-check and update README.
Things I noticed:

1. https://github.com/poanetwork/bridge-nodejs#how-to-use - "Deploy bridge contracts" says to use `v2` branch of bridge contracts, while it should be `refactor_v1`. (deployment steps are not working for `v2` anyway)
2. https://github.com/poanetwork/bridge-nodejs#run-the-processes - `sendUserTx*` scripts are in `scripts/`, not in `tests/`. They also require a copy of `.env` to be in `scripts/` to run properly.

**Comment by fvictorio** [comment]
> 2\. They also require a copy of `.env` to be in `scripts/` to run properly.

Either that or run the script from the root directory (`node scripts/sendUserTxToHome.js`). But I'll make a quick PR to allow running the script from anywhere.

**Comment by akolotov** [comment]
Addressed in #92
